[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "setuptools_scm[toml]>=3.4",
  "cython",
  "numpy<1.22",
]
[tool.setuptools_scm]
write_to = "gmprocess/version.py"
write_to_template = '__version__ = "{version}"'
# tag_regex = r"^(?P<prefix>v)?(?P<version>[^\+]+)(?P<suffix>.*)?$"
